### ISSUE TITLE
bug found with echo

### ISSUE THREAD

**Issue by tblaase** [toni-schmitt/minishell#12]
**Describe the bug**

**To Reproduce**
1. Run `echo "-n Hello this is a test if echo is leaking"`
2. there is no output printed

**Expected behavior**
output should look like `-n Hello this is a test if echo is leaking`

probably there is more errors with ' and " than just this one

**Comment by toni-schmitt** [comment]
Error found: Needed to compare whole argument with "-n" 
<img width="394" alt="image" src="https://user-images.githubusercontent.com/25370820/141167926-85a55751-d022-4781-af30-32e4aaa87d28.png">
corresponding commit: https://github.com/toni-schmitt/minishell/commit/0ff96d03f8632e7c74bbe7365323c99f53b43a8f
