### ISSUE TITLE
Only heredoc without commands fails with segmentation fault

### ISSUE THREAD

**Issue by toni-schmitt** [toni-schmitt/minishell#17]
**Describe the bug**
<img width="318" alt="image" src="https://user-images.githubusercontent.com/25370820/145679235-c0aa05c1-8a05-474b-a16f-f64df54fb897.png">

**To Reproduce**
1. Execute minishell
2. Execute heredoc ("<< end")
3. Pass input and eof

**Comment by toni-schmitt** [comment]
also happens in this context:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/25370820/145679275-4906b4bc-7da9-4091-af50-99286cd70de2.png">
@tblaase  please debug this since i cannot debug with prompts on macos

**Comment by tblaase** [comment]
fixed :) now is working as bash
no fd's are staying open
