### ISSUE TITLE
echo not working correctly when handed '\0'

### ISSUE THREAD

**Issue by toni-schmitt** [toni-schmitt/minishell#18]
**Describe the bug**
When giving input with double quotes text and double quotes text in the middle gets lost

**To Reproduce**
1. Type into minishell: `""hi""`
2. See wrong output

**Expected behavior**
Output should be `hi` not empty
Hanlde quotes differently! Quote tokens should be split like this (considering input from above):
`""`
`hi`
`""`

**Screenshots**
<img width="177" alt="image" src="https://user-images.githubusercontent.com/25370820/145684623-4166fa56-e104-467f-be67-8d247ad66d01.png">

**Comment by tblaase** [comment]
partly fixed, now echo ""hi"" doesn't skip hi anymore, but an additional space is printed at the beginning of the line
![grafik](https://user-images.githubusercontent.com/85116019/145689847-041605b1-439d-4b7c-995a-3a95205be624.png)

**Comment by tblaase** [comment]
i tried to fix echo but i broke everythin while trying, so since you wrote echo it's yours now :)

**Comment by tblaase** [comment]
so error is now that if you have an argument only containing '\0' echo will print " "

**Comment by toni-schmitt** [comment]
fixed now there will be only spaces printed if last string was not empty
correspoinding commit: https://github.com/toni-schmitt/minishell/commit/efadb6f4e58c3b8110815d2969998eca667c1957
