### ISSUE TITLE
CTRL + [KEY] printing ^[KEY]

### ISSUE THREAD

**Issue by toni-schmitt** [toni-schmitt/minishell#19]
**Describe the bug**
When pressing `CTRL + [KEY]` minishell also prints `^[KEY]`

**To Reproduce**
1. Press `CTRL + D` (for example) while running minishell
2. See error

**Expected behavior**
`^[KEY]` should not print

**Screenshots**
<img width="295" alt="image" src="https://user-images.githubusercontent.com/25370820/145684733-eb9a9131-8f63-4d92-b1fb-ebcb6eb6c459.png">

**Comment by tblaase** [comment]
my bash is doing the same 🥲 
![grafik](https://user-images.githubusercontent.com/85116019/145691398-12424aea-32be-4436-957a-ccc3a05c17ec.png)

**Comment by tblaase** [comment]
nevermind, bash 3.2 is not printing keystrokes of `ctrl+C` or `ctrl+C`
only the newer version of bash has this behavior

**Comment by toni-schmitt** [comment]
fixed it, now `stty -echoctl` gets called with executor before anything else
https://github.com/toni-schmitt/minishell/commit/4d511c52903215d1f2c7e38277a032cc1d90213a
