### ISSUE TITLE
$VAR interpretation having problems interpreting non existant variables

### ISSUE THREAD

**Issue by tblaase** [toni-schmitt/minishell#20]
**Describe the bug**
when using som $VAR stuff that is not existing in our minishell like $$ it is double freeing

**To Reproduce**
1. run `echo $$`
2. now broken 😭 

**Expected behavior**
should just treat it as a string

**Screenshots**
![grafik](https://user-images.githubusercontent.com/85116019/145691276-4abf0ae0-b746-41ff-9446-4616747131e8.png)

**Additional context**
i found that the double free happens in `interprete_env_var.c` on line 96 in `get_var`

**Comment by tblaase** [comment]
`$OLDPWD` is not working at all even if it is existing

**Comment by toni-schmitt** [comment]
Fixed pointer beeing freed was not allocated, now pointer address does not get changed!
Corresponding commit: [b84db45113f53dde373bc89a21100edff0055fdc](https://github.com/toni-schmitt/minishell/commit/b84db45113f53dde373bc89a21100edff0055fdc)
