### ISSUE TITLE
detecting subshell and trying to run it even if it is input error

### ISSUE THREAD

**Issue by tblaase** [toni-schmitt/minishell#23]
**Describe the bug**
if you run `echo test (cat |wc)` it detects a subshell

**To Reproduce**
1. enable prnt_tokens in parser
2. run `echo test (cat |wc)`
3. See error

**Expected behavior**
input error

**Screenshots**
this is output now (subshell not working right now)
<img width="286" alt="Screen Shot 2021-12-13 at 2 49 03 PM" src="https://user-images.githubusercontent.com/85116019/145825302-a4b1d096-9a9b-4ed8-a480-815d323ac3af.png">

this should be the output
<img width="321" alt="Screen Shot 2021-12-13 at 2 57 46 PM" src="https://user-images.githubusercontent.com/85116019/145825402-0ccc9b2c-02cd-43cd-8643-b7c6d10d33d3.png">

**Additional context**
problem seems to be in parser

**Comment by toni-schmitt** [comment]
fixed
corresponding commit: https://github.com/toni-schmitt/minishell/commit/8be0b3a923d4828e35e7fbaeb124af29c3dbc1ad
