### ISSUE TITLE
segfaulting when running only subshell

### ISSUE THREAD

**Issue by tblaase** [toni-schmitt/minishell#25]
**Describe the bug**
when running nothing but a subshell it segfaults in is_valid_syntax !is_special line 116 of check syntax

**To Reproduce**
1. run `(echo hi | wc)
2. See error

**Expected behavior**
just run the command

**Screenshots**
here is the position of the callstack where it is failing
<img width="785" alt="Screen Shot 2021-12-14 at 12 58 25 PM" src="https://user-images.githubusercontent.com/85116019/145994172-df3c1965-844d-4ece-ae2b-7d5431fd22cc.png">

here is the segfault
<img width="349" alt="Screen Shot 2021-12-14 at 1 01 39 PM" src="https://user-images.githubusercontent.com/85116019/145994617-784a1d3e-743a-4d8d-b589-0da75b93dbcd.png">

**Comment by toni-schmitt** [comment]
fixed with commit https://github.com/toni-schmitt/minishell/commit/31abd1294a372e4e7616048407db9981c972a725 now added protection aginst segfault
