### ISSUE TITLE
minishell segfaulting when doing weird stuff with $VARS

### ISSUE THREAD

**Issue by tblaase** [toni-schmitt/minishell#26]
**Describe the bug**

**To Reproduce**
1. run `export fun+exit`
2. run `$fun`
3. See error segfault

**Expected behavior**
should treat the value in this case as command
<img width="195" alt="Screen Shot 2021-12-14 at 4 27 46 PM" src="https://user-images.githubusercontent.com/85116019/146027883-7752c270-a9cc-4769-a080-c3a18aad9d0b.png">

**Screenshots**
here is our segfault
<img width="400" alt="Screen Shot 2021-12-14 at 4 28 19 PM" src="https://user-images.githubusercontent.com/85116019/146028010-4b36c320-b846-40ac-950a-198f091d66c9.png">

**Comment by toni-schmitt** [comment]
fixed
