### ISSUE TITLE
minishell exiting itself

### ISSUE THREAD

**Issue by tblaase** [toni-schmitt/minishell#29]
**Describe the bug**
after executing it exits itself with printing exit

**To Reproduce**
1. run `abc | echo hi >file2 | wc`
2. See error

**Expected behavior**

**Screenshots**
![grafik](https://user-images.githubusercontent.com/85116019/146250381-5ff5ac61-e5ec-486a-b9ea-f6caaf609dd4.png)

**Additional context**

**Comment by tblaase** [comment]
after wc buff of readline is NULL and it goes into exit routine

**Comment by toni-schmitt** [comment]
Exit gets called because `buf` (main.c:50) was NULL.

**Comment by toni-schmitt** [comment]
Maybe check if some output or fds of the piping mess this up, can't really debug because of mac

**Comment by tblaase** [comment]
fixed in commit `c915449`

**Comment by tblaase** [comment]
now not working anymore...
![grafik](https://user-images.githubusercontent.com/85116019/146686767-d68ba026-8d5a-41a8-b0ca-f2e1f863dcc4.png)

**Comment by toni-schmitt** [comment]
pipes must still be open since readline does not wait for input, and buf gets set to NULL instantly

**Comment by toni-schmitt** [comment]
I myself have no leaks despite running it multiple times...
![image](https://user-images.githubusercontent.com/25370820/146687689-89f58cf5-081e-460d-a19f-368681210d59.png)

**Comment by toni-schmitt** [comment]
![image](https://user-images.githubusercontent.com/25370820/146696051-76237d88-37ec-4221-a898-66e6e60c773a.png)
error also happens with redirections with valid commands, probably only happens with inbuilt redirections

**Comment by toni-schmitt** [comment]
![image](https://user-images.githubusercontent.com/25370820/146696106-6a8c42ac-b062-4279-bf0b-f93808c9ba1c.png)
does not happen on non inbuilt redirections

**Comment by toni-schmitt** [comment]
Inbuilt-piping does not work, inbuilt just print to stdout and do not reset stdin at the end
![image](https://user-images.githubusercontent.com/25370820/146696942-933ae22c-7eaa-449d-8957-99e0ac564bef.png)

**Comment by toni-schmitt** [comment]
![image](https://user-images.githubusercontent.com/25370820/146697470-94a0fd8d-324a-4f55-a9d2-baa197cad9c9.png)
probably fixed error by also duplicating stdin fd, and closing it the same way it was done with stdout fd

**Comment by tblaase** [comment]
issue is gone, so your fix looks like it worked
