### ISSUE TITLE
wildcard * is not working as intended

### ISSUE THREAD

**Issue by tblaase** [toni-schmitt/minishell#30]
**Describe the bug**
Wildcard alsways is all stuff from directory

**To Reproduce**
look at what minishell does in screenshot and compare it to what bash does

**Expected behavior**
look st the screenshot

**Screenshots**
![grafik](https://user-images.githubusercontent.com/85116019/146252112-ac87b398-2625-4c8c-a55b-0b279babddf3.png)

**Additional context**

**Comment by toni-schmitt** [comment]
minishell 2.0 of jsilla and nschumac also do not interpet `*`*
Maybe think about just ignoring it
<img width="374" alt="image" src="https://user-images.githubusercontent.com/25370820/146271243-cf53c6dc-1f41-4bf4-8136-7aac8b297966.png">
