### ISSUE TITLE
quotes not working 100%

### ISSUE THREAD

**Issue by tblaase** [toni-schmitt/minishell#31]
**Describe the bug**
$VARS that should be interpreted are not interpreted
when the outside quotes are `"` $VARS are interpreted if outside quotes are `'` they should just be treated as a string

**To Reproduce**
1. run `echo "'$USER'"`
2. See error

**Expected behavior**

**Screenshots**
this is our minishell
![grafik](https://user-images.githubusercontent.com/85116019/146253905-25b3e14f-4910-4adb-a364-2160bbfff719.png)

this is bash
![grafik](https://user-images.githubusercontent.com/85116019/146254035-3cc542ae-78d1-46f0-b0d4-512866e1775b.png)

**Comment by toni-schmitt** [comment]
Please have a look at commit https://github.com/toni-schmitt/minishell/commit/02c27f0e1fc9f2bac32c03d6a627fbe858b25115 `get_env_var_value` overwrites lex_tok on allocation

**Comment by toni-schmitt** [comment]
lex_tok gets overwritten after get_env_var_value call
<img width="370" alt="image" src="https://user-images.githubusercontent.com/25370820/146280798-3167cd59-544a-4a74-95d3-f142aa1df1a1.png">

**Comment by toni-schmitt** [comment]
awesome thank you, gonna look right into it when im in school!

**Comment by tblaase** [comment]
i think removing the free(lex_tok) from interprete_env_var.c (get_var) line 78 fixed it

**Comment by tblaase** [comment]
removing the previously mentioned free fixed the overwriting and is not leaking
