### ISSUE TITLE
weird behaviour when giving empty quotes as argument

### ISSUE THREAD

**Issue by tblaase** [toni-schmitt/minishell#35]
**Describe the bug**
can't debug this with macOS, when running empty quotes as an argument it prints Permission denied and exits with -1 but not while debugging on macOS.
So debug on Linux!!!

**To Reproduce**
1. run `""` or `''`
2. run `echo $?`
3. See error

**Expected behavior**
should print `command not found` and exit with `127`

**Screenshots**
minishell:
<img width="180" alt="Screen Shot 2021-12-16 at 8 32 30 PM" src="https://user-images.githubusercontent.com/85116019/146436551-024d6888-0c65-43e4-b742-fbfd286d0932.png">

bash:
<img width="201" alt="Screen Shot 2021-12-16 at 8 32 55 PM" src="https://user-images.githubusercontent.com/85116019/146436604-5146646c-969c-4782-a205-08d76e519971.png">

**Additional context**
debugging in Linux should give clarity what happens and why
if it doesn't, add a special case `if (ft_strlen(cmd)==0) return (cmd_not_found)`

**Comment by tblaase** [comment]
addition: for some reson there is now a minishell inside minishell running

**Comment by toni-schmitt** [comment]
fixed with https://github.com/toni-schmitt/minishell/commit/1ac2ba97beb89d627b99100aa7353b6e99ffa579
