### ISSUE TITLE
minishell thinking `ft_strlen(lex_tok)` is a subshell for some reason

### ISSUE THREAD

**Issue by tblaase** [toni-schmitt/minishell#37]
**Describe the bug**
minishell thinking `ft_strlen(lex_tok)` is a subshell for some reason
while debugging i noticed it goes into the `expander` and from there into the `subshell function`

**To Reproduce**
1. run `ft_strlen(lex_tok)`
2. See error

**Expected behavior**
syntax error

**Screenshots**
however this happens, it should not get past `syntax check`
<img width="319" alt="Screen Shot 2021-12-16 at 10 36 47 PM" src="https://user-images.githubusercontent.com/85116019/146452612-a3b5c178-c3ce-4e4c-8be4-3b5722f7098a.png">

**Comment by toni-schmitt** [comment]
Now this gets handeld by `is_valid_line_syntax` https://github.com/toni-schmitt/minishell/commit/a59cb3015159f670c562f75b2937f1811ec43652
