### ISSUE TITLE
echo * does segfault with valgrind

### ISSUE THREAD

**Issue by tblaase** [toni-schmitt/minishell#38]
**Describe the bug**
running `echo *` with valgrind shows errors and just segfaults the minishell

**To Reproduce**
1. run `valgrind --leak-check=full --track-origins=yes ./minishell`
2. run `echo *`
2. See error

**Expected behavior**
print all the folders and files from the current directory.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/85116019/146515261-c29df801-6776-4965-a1ba-b3483a5966ce.png)
![grafik](https://user-images.githubusercontent.com/85116019/146515337-9e56edfa-f081-4cb3-aeff-a10d1be1fc17.png)
![grafik](https://user-images.githubusercontent.com/85116019/146515402-a0184816-d85b-495d-ab20-8ee3aed98697.png)

**Additional context**
Maybe @toni-schmitt you can find the mistake with the added traces of valgrind.

**Comment by toni-schmitt** [comment]
fixed with commit https://github.com/toni-schmitt/minishell/commit/5f99e806427ead9641bc1fccce77f6a45f31a7d4 by initializing value `items`
