### ISSUE TITLE
combination of && and || does not work properly

### ISSUE THREAD

**Issue by tblaase** [toni-schmitt/minishell#39]
**Describe the bug**
when running `cat Makefile | grep PATH >file1 && cat <file1 && wc file1 && false && echo hi || cat <<eof` the output of the last cat which should print the heredoc is not printed but it should

**To Reproduce**
1. run `cat Makefile | grep PATH >file1 && cat <file1 && wc file1 && false && echo hi || cat <<eof`
2. Compare output to bash
3. See error

**Expected behavior**
The output from `cat <<eof` is not printed but should be printed, at least my bash prints it

**Screenshots**
![grafik](https://user-images.githubusercontent.com/85116019/146521543-1d10557b-0cd7-4111-b20d-1dbe207410b8.png)
after the red line there should be the output of the heredoc but it isn't

this is the output from my bash, ignore the can't overwrite file
![grafik](https://user-images.githubusercontent.com/85116019/146521910-cb03c922-2058-41b3-b822-f13264b338bf.png)

**Additional context**

**Comment by toni-schmitt** [comment]
![image](https://user-images.githubusercontent.com/25370820/146555759-fd3d0431-fcd2-4041-86fb-9472c62042a2.png)
In bash and zsh aswell the output does not get prtined, so everything works as intendet, if the command output from the last command is 0 and || is used, the next command should not get executed.

**Comment by tblaase** [comment]
you understood it wrong, pls test ´echo hi && false && echo hi2 || echo hi3`

**Comment by toni-schmitt** [comment]
Since this is a very special case (refering to subject.pdf: "_Anything not asked is not required._") this will not be fixed. Also because fixing this requires the whole expander to be rewritten.
Also heredoc expansion with reading is not asked from subject.pdf ("_“<<” read input from the current source until a line containing only the delimiter is seen. it doesn’t need to update history!_")

**Comment by toni-schmitt** [comment]
Sorry I am stupid, this is very valid

**Comment by toni-schmitt** [comment]
bash 3.2 also handels it like this, gonna fix it real quick!
![image](https://user-images.githubusercontent.com/25370820/146568985-1aeda314-211e-4f6d-bec8-9e1d25612d1f.png)

**Comment by toni-schmitt** [comment]
minishell now also handels it like bash!
![image](https://user-images.githubusercontent.com/25370820/146569169-26599d99-b9a0-4f6c-a4e2-9dc98fedd9ac.png)

https://github.com/toni-schmitt/minishell/commit/9e002c2593335c2cd75ab0bc6e59cf1d6c8146d8
