### ISSUE TITLE
all subshells fail to run and exit with invalid syntax

### ISSUE THREAD

**Issue by tblaase** [toni-schmitt/minishell#40]
**Describe the bug**
all subshells i tested, even valid ones are not working

**To Reproduce**
1. run any command containing a subshell
2. See error

**Expected behavior**
run valid subshells

**Screenshots**

**Additional context**

**Comment by toni-schmitt** [comment]
fixed with https://github.com/toni-schmitt/minishell/commit/aed7505d6048e5e09b65016b3f2feda5a196295e and  https://github.com/toni-schmitt/minishell/commit/40918f8fb646834f0e339f27a80aa63ef4d0ea86
