### ISSUE TITLE
double free and abort

### ISSUE THREAD

**Issue by tblaase** [toni-schmitt/minishell#41]
**Describe the bug**
when first running `print` and then running `print("hi")` minishell aborts with a double free, check traces in screenshot

**To Reproduce**
1. run `print`
2. run `print("hi")`
3. See error

**Expected behavior**
only printing invalid syntax and then returning to prompt

**Screenshots**
minishell:
![grafik](https://user-images.githubusercontent.com/85116019/146638615-e4137b40-03b5-4315-aa1c-35fe6d03b8a4.png)

bash:
![grafik](https://user-images.githubusercontent.com/85116019/146638635-758830f2-71a9-4018-b7e2-f30976c383d4.png)

**Additional context**
traces from valgrind:
![grafik](https://user-images.githubusercontent.com/85116019/146638665-2581e2db-7328-4c99-ab87-36683f7cf999.png)
![grafik](https://user-images.githubusercontent.com/85116019/146638674-42f9b751-86a3-46ec-a01c-ef4a4580519a.png)

all traces point to sth in lexer and exit_on_syntax_error

**Comment by toni-schmitt** [comment]
![image](https://user-images.githubusercontent.com/25370820/146647441-b2283295-bb37-450a-9f2e-25dea58201de.png)
could not reproduce, maybe tested on an old version? @tblaase

**Comment by tblaase** [comment]
yes, now working without any problems, maybe used an old version for some reason 🤷‍♂️ 
was't able to reproduce it as well
![grafik](https://user-images.githubusercontent.com/85116019/146683880-71bdc3e4-bf2e-4879-a4f4-987f061a3a0a.png)

considering it as fixed by unknown commit 😄
