### ISSUE TITLE
only using a closing parenthesis causes infinite loop

### ISSUE THREAD

**Issue by tblaase** [toni-schmitt/minishell#42]
**Describe the bug**
only using a closing parenthesis doesn't get detected as invalid syntax and causes an infinite loop

**To Reproduce**
1. run `echo hi && echo ciao)`
2. See error

**Expected behavior**
should be invalid syntax

**Screenshots**
![grafik](https://user-images.githubusercontent.com/85116019/146638840-7fde296b-530b-4ca2-b61e-9541d15a121f.png)

**Comment by toni-schmitt** [comment]
fixed with https://github.com/toni-schmitt/minishell/commit/a94fba600f099e7a63fcb58040eb26a726c12ff7
