### ISSUE TITLE
Commands with \ will not work and get interpreted as syntax error

### ISSUE THREAD

**Issue by toni-schmitt** [toni-schmitt/minishell#43]
**Describe the bug**
Commands where a `\` is included will get interpreted as syntax error due to https://github.com/toni-schmitt/minishell/blob/8f74422813354de6a79dac4bd23b9aa47a6533cc/src/brain/utils/lexer_utils/check_line_syntax.c#L67 and subject.pdf saying "_Not interpret unclosed quotes or unspecified special characters like \ or ;._". Should this be considered syntax error or should this be interpreted as a string? Unclosed quotes and semicolons get interpreted as syntax error right now.

**To Reproduce**
1. Run `printf hi\n`
2. See syntax error

**Screenshots**
![image](https://user-images.githubusercontent.com/25370820/146654543-18dfe758-3653-4592-b52b-4656b1c13798.png)

**Comment by tblaase** [comment]
handing it encased in `""` or `''` will still work, so i would say its fine as it is :+1:
