### ISSUE TITLE
subshell not working correctly and leaking

### ISSUE THREAD

**Issue by tblaase** [toni-schmitt/minishell#46]
**Describe the bug**
when running a command containing a subshell it creates a leak and cuts part of the subshell command

**To Reproduce**
1. run `echo hi && (echo this is subshell)`
2. See error

**Expected behavior**
don't cut the end of the command and don't leak

**Screenshots**
minishell:
![grafik](https://user-images.githubusercontent.com/85116019/146686372-e32c5d23-eeb8-4300-b86b-0a18256fc41b.png)

**Additional context**
Added the traces of valgrind and tested running without valgrind lead to the same behavior.

**Comment by toni-schmitt** [comment]
currently working on this already, found some more issues with subshell, trying to fix them right now
