### ISSUE TITLE
Piping into cd will change current working directory to home directory

### ISSUE THREAD

**Issue by toni-schmitt** [toni-schmitt/minishell#47]
**Describe the bug**
When piping into cd command, it changed current working directory to home directory

**To Reproduce**
1. Run `echo hi | pwd | cd`
2. See error

**Expected behavior**
cd should not change directory

**Screenshots**
minishell:
![image](https://user-images.githubusercontent.com/25370820/146697648-e9c56bf4-1c67-4083-8ad1-05dc011646cc.png)
bash: 
![image](https://user-images.githubusercontent.com/25370820/146697668-1c8d0d1a-9324-47af-93a7-9ee808ee4771.png)

**Comment by tblaase** [comment]
cd can't read from stdin and receives NULL as argv[1] so it goes into home directory

**Comment by tblaase** [comment]
but cd should have no effect on parent process when run in pipes, because it should be executed in a child process
keep investigating

**Comment by tblaase** [comment]
our inbuilt functions are never run inside a child process......

**Comment by tblaase** [comment]
having trouble with expander_tokens and wrong memory access, need help

**Comment by tblaase** [comment]
closed with 04427dd
