### ISSUE TITLE
Minishell trying to open wrong in file if heredoc is there

### ISSUE THREAD

**Issue by toni-schmitt** [toni-schmitt/minishell#48]
**Describe the bug**
When running `cat << eof < file1` minishell trys to open eof thinking its a file.

**To Reproduce**
1. Run `cat << eof < file1`
2. See error

**Expected behavior**
eof should not be opened

**Screenshots**
minishell: 
`eof` output is from a debug print added here: https://github.com/toni-schmitt/minishell/blob/b27256ddde0fda9c62b08cc8948448c73337cef1/src/brain/utils/expander_utils/handle_redirs_utils.c#L34-L35
![image](https://user-images.githubusercontent.com/25370820/146698278-863843fe-4910-4e7c-8f42-78c99c6a3b73.png)

![image](https://user-images.githubusercontent.com/25370820/146698153-a3e780af-385d-4e9e-ae67-e6dd4d761361.png)
bash:
![image](https://user-images.githubusercontent.com/25370820/146698162-ac8f92c3-5a2b-4682-8666-f0ed58180898.png)

**Additional context**
Also happens in these contexts:
![image](https://user-images.githubusercontent.com/25370820/146698361-873ed318-142e-45fd-be8a-f639ed057803.png)

**Comment by tblaase** [comment]
fixed with commit 6230cc7
